Version 4
SymbolType BLOCK
RECTANGLE Normal -96 -64 96 80
PIN -96 -16 LEFT 8
PINATTR PinName A
PINATTR SpiceOrder 1
PIN -96 32 LEFT 8
PINATTR PinName B
PINATTR SpiceOrder 2
PIN 0 80 VLEFT 8
PINATTR PinName GND
PINATTR SpiceOrder 3
PIN 0 -64 VRIGHT 8
PINATTR PinName VDD
PINATTR SpiceOrder 4
PIN 96 0 RIGHT 8
PINATTR PinName XOR_OUT
PINATTR SpiceOrder 5
